kind: pipeline
name: Go latest validation

platform:
  os: linux
  arch: amd64

steps:
  - name: Build Latest Go
    image: golang:latest
    commands:
      - go build
      - go test ./...
  - name: Build Go 1.20
    image: golang:1.20
    commands:
      - go build
      - go test ./...
