kind: pipeline
name: Go latest validation

platform:
  os: linux
  arch: amd64

pipeline:
  build_go_1.23:
    image: golang:1.23.2
    commands:
      - go build
      - go test -v
    environment:
      CI: "drone"
  build_go_1.20:
    image: golang:1.20.14
    commands:
      - go build
      - go test -v
    environment:
      CI: "drone"
