kind: pipeline
name: Go 1.23.2 validation

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: golang:1.23.2
    commands:
      - go build
      - go test -v

---
kind: pipeline
name: Go 1.20.14 validation

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: golang:1.20.14
    commands:
      - go build
      - go test -v
