kind: pipeline
name: Go latest validation

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: golang:latest
    commands:
      - go build
      - go test -v

---
kind: pipeline
name: Go 1.20 validation

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: golang:1.20
    commands:
      - go build
      - go test -v
